name: Build and Test

on:
   pull_request:
      branches:
         - main
   push:
      branches:
         - main
permissions:
   contents: read

jobs:
   build:
      runs-on: ${{ matrix.os }}
      strategy:
         matrix:
            os: [ubuntu-latest, windows-latest]
      concurrency:
         group: build-and-test-${{ github.ref_name }}-${{ matrix.os }}
         cancel-in-progress: true

      steps:
         - name: Checkout repository
           uses: actions/checkout@v4

         - name: Setup Node.js
           uses: actions/setup-node@v4
           with:
              node-version: "22.x"

         - name: Install pnpm
           run: npm install -g pnpm

         - name: Install dependencies & test
           run: pnpm it --no-frozen-lockfile